# Generated by Django 4.0.6 on 2022-07-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filemanager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('parent_id', models.IntegerField(default=0)),
                ('last_update', models.DateField(auto_now=True)),
                ('size', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('file_path', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filemanager_hosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.IntegerField()),
                ('hosting_name', models.CharField(max_length=255)),
                ('hosting_file_id', models.CharField(max_length=255)),
            ],
        ),
    ]
